apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-server-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudl-server
    spec:
      containers:
        - name: cloudl-server
          image: almar98/backend-image:v1
          ports:
            - containerPort: 5000
              name: nodejs-port
  selector:
    matchLabels:
      app: cloudl-server